const events = [
  {
    day: 1,
    name: "Opening Ceremonies",
    type: "Main Event",
    location: "what channel?",
    startTime: "7:00pm",
    endTime: "8:00pm",
  },
  {
    day: 1,
    name: "Huawei event",
    type: "Workshop",
    location: "what channel?",
    startTime: "8:00pm",
    endTime: "8:45pm",
  },
  {
    day: 1,
    name: "Team Formation",
    type: "Main Event",
    location: "what channel?",
    startTime: "9:00pm",
    endTime: "10:00pm",
  },
  {
    day: 1,
    name: "Hacking Begins",
    type: "Main Event",
    location: "what channel?",
    startTime: "9:00pm",
    endTime: null,
  },
  {
    day: 1,
    name: "Web Dev Workshop",
    type: "Workshop",
    location: "what channel?",
    startTime: "10:00pm",
    endTime: "11:00pm",
  },
  {
    day: 2,
    name: "Midnight Activity 1: Geoguesser",
    type: "Activity",
    location: "what channel?",
    startTime: "12:00am",
    endTime: "12:30am",
    description: "description",
  },
  {
    day: 2,
    name: "Wellness hour",
    type: "Activity",
    location: "what channel?",
    startTime: "1:00am",
    endTime: "2:00am",
  },
  {
    day: 2,
    name: "Coffee hour",
    type: "Activity",
    location: "what channel?",
    startTime: "8:00am",
    endTime: "9:00am",
  },
  {
    day: 2,
    name: "Yoga ",
    type: "Activity",
    location: "what channel?",
    startTime: "8:30am",
    endTime: "9:30am",
  },
  {
    day: 2,
    name: "Scavenger Hunt",
    type: "Activity",
    location: "what channel?",
    startTime: "9:45am",
    endTime: "10:30am",
  },
  {
    day: 2,
    name: "FDM Group Workshop",
    type: "Workshop",
    location: "what channel?",
    startTime: "10:30am",
    endTime: "11:00am",
  },
  {
    day: 2,
    name: "Big Bang Workshop",
    type: "Workshop",
    location: "what channel?",
    startTime: "11:00am",
    endTime: "11:30am",
  },
  {
    day: 2,
    name: "Biztree Workshop",
    type: "Workshop",
    location: "what channel?",
    startTime: "11:30am",
    endTime: "12:30pm",
  },
  {
    day: 2,
    name: "Speed Networking",
    type: "Activity",
    location: "what channel?",
    startTime: "1:00pm",
    endTime: "3:00pm",
  },
  {
    day: 2,
    name: "Math/Logic Competition",
    type: "Activity",
    location: "what channel?",
    startTime: "2:00pm",
    endTime: "3:00pm",
  },
  {
    day: 2,
    name: "Design Workshop",
    type: "Workshop",
    location: "what channel?",
    startTime: "3:00pm",
    endTime: "4:00pm",
  },
  {
    day: 2,
    name: "MLH Powerpoint Karaoke",
    type: "Activity",
    location: "what channel?",
    startTime: "4:15pm",
    endTime: "5:00pm",
  },
  {
    day: 2,
    name: "Cooking",
    type: "Activity",
    location: "what channel?",
    startTime: "6:00pm",
    endTime: "7:00pm",
  },
  {
    day: 2,
    name: "Trivia",
    type: "Activity",
    location: "what channel?",
    startTime: "7:15pm",
    endTime: "8:00pm",
  },
  {
    day: 2,
    name: "Netflix Movie Party",
    type: "Activity",
    location: "what channel?",
    startTime: "8:00pm",
    endTime: "10:00pm",
  },
  {
    day: 2,
    name: "Youtube Movie Party",
    type: "Activity",
    location: "what channel?",
    startTime: "8:00pm",
    endTime: "10:00pm",
  },
  {
    day: 3,
    name: "Midnight Activity 2: Geoguesser",
    type: "Activity",
    location: "what channel?",
    startTime: "12:00am",
    endTime: "12:30am",
    description: "description",
  },
  {
    day: 3,
    name: "Hacking Ends",
    type: "Main Event",
    location: "what channel?",
    startTime: "9:00am",
    endTime: null,
    description: "description",
  },
  {
    day: 3,
    name: "Closing Ceremonies",
    type: "Main Event",
    location: "what channel?",
    startTime: "1:30pm",
    endTime: "2:30pm",
  },
]

export default events
